import { Todo } from './types'

const mockTodos: Todo[] = [
  {
    id: '1',
    title: 'Set up CI/CD pipeline',
    description: 'Configure GitHub Actions for automated tests, builds, and staging deploys.',
    priority: 'high',
    dueDate: '2026-03-10',
    assignee: 'Riya Sharma',
    status: 'in-progress',
    createdAt: '2026-03-01',
  },
  {
    id: '2',
    title: 'Refactor auth middleware',
    description: 'Simplify JWT validation and add refresh token rotation support.',
    priority: 'medium',
    dueDate: '2026-03-28',
    assignee: 'Alex Chen',
    status: 'todo',
    createdAt: '2026-03-05',
  },
  {
    id: '3',
    title: 'Design new dashboard widgets',
    description: 'Create analytics widgets for active users, churn, and MRR trends.',
    priority: 'low',
    dueDate: '2026-04-05',
    assignee: 'Priya Nair',
    status: 'todo',
    createdAt: '2026-03-07',
  },
  {
    id: '4',
    title: 'Fix invoice export bug',
    description: 'Resolve CSV formatting issue for multi-currency invoices.',
    priority: 'high',
    dueDate: '2026-03-14',
    assignee: 'Omar Khan',
    status: 'todo',
    createdAt: '2026-03-08',
  },
  {
    id: '5',
    title: 'Update onboarding email series',
    description: 'Rewrite email copy and add personalization fields for product fit.',
    priority: 'medium',
    dueDate: '2026-03-22',
    assignee: 'Riya Sharma',
    status: 'in-progress',
    createdAt: '2026-03-09',
  },
  {
    id: '6',
    title: 'Improve query performance',
    description: 'Add indexes for audit log table and optimize slow reports.',
    priority: 'high',
    dueDate: '2026-03-12',
    assignee: 'Alex Chen',
    status: 'done',
    createdAt: '2026-02-26',
  },
  {
    id: '7',
    title: 'Mobile header polish',
    description: 'Adjust spacing and icon alignment for small screen breakpoints.',
    priority: 'low',
    dueDate: '2026-04-02',
    assignee: 'Priya Nair',
    status: 'in-progress',
    createdAt: '2026-03-04',
  },
  {
    id: '8',
    title: 'Audit error logging',
    description: 'Review Sentry alerts and add breadcrumbs for billing flows.',
    priority: 'medium',
    dueDate: '2026-03-09',
    assignee: 'Omar Khan',
    status: 'todo',
    createdAt: '2026-02-27',
  },
]

export default mockTodos
